scan_interval:
  period: 10
  unit: seconds
server_config:
  context_root: '/health/prometheus'
  port: 9095
services:
  - name: 'test'
    path: 'http://localhost:8585/management/health'
  - name: 'test2'
    path: 'http://localhost:8586/management/health'
#    ca_file_path: ''

